### PR TITLE
Update sonarrV3.css

### PR DESCRIPTION
**Pull request by Cookie-Monster-Coder**
Added CSS for added date.

### CODE REVIEW

**Comment by Archmonger** [comment]
What page within sonarr does this CSS apply to?

**Comment by cookie-monster-bit** [comment]
> 
> 
> What page within sonarr does this CSS apply to?

The Series page, underneath the quality profile name, it has the added date ex: "Added Oct 4 2020"

EDIT: I think you need to sort by Added to see it

**Comment by Archmonger** [comment]
You accidentally added your code to the section dedicated to "Navbar" styling. I've moved it out of there and put it into "Posters"

**Comment by Archmonger** [comment]
Also, in the future please use more a more verbose commit message than "Update sonarrV3.css".

Thanks for the commit!

**Pull request merged**
